name: Godot Headless Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  headless-check:
    name: Headless Project Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot binary
        id: godot-cache
        uses: actions/cache@v3
        with:
          path: godot
          key: godot-4.4.1-linux

      - name: Download Godot if not cached
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          wget -O godot.zip https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.4.1-stable_linux.x86_64

      - name: Headless smoke test with filtered stderr check
        run: |
          mkdir -p .godot_ci_config

          # Run Godot and separate stdout and stderr
          ./godot/Godot_v4.4.1-stable_linux.x86_64 \
            --headless --editor --quit --path . \
            --editor-settings-path .godot_ci_config \
            1> godot_stdout.log 2> godot_stderr_raw.log

          echo "--- Raw STDERR ---"
          cat godot_stderr_raw.log || true

          # Remove harmless GitPlugin + VCS error blocks (2 lines each)
          awk '
            /ERROR: Cannot get class .GitPlugin./ { getline; next }
            /ERROR: Received a nullptr VCS extension/ { getline; next }
            { print }
          ' godot_stderr_raw.log > godot_stderr_clean.log

          echo "--- Cleaned STDERR ---"
          cat godot_stderr_clean.log || true

          # Fail if any real errors remain
          if [ -s godot_stderr_clean.log ]; then
            echo "::error title=Godot Check::Detected critical errors in cleaned stderr output"
            exit 1
          else
            echo "✅ No critical stderr errors found."
          fi
