name: Godot Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Godot Headless
      run: |
        curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux_headless.64.zip
        unzip godot.zip
        chmod +x Godot_v4.2.1-stable_linux_headless.64

    - name: Run Godot build
      run: ./Godot_v4.2.1-stable_linux_headless.64 --headless --build-solutions
