name: Build and Smoke Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Godot Project
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons python3-pip
          pip3 install pytest

      - name: Build Godot (Headless)
        run: |
          scons platform=linux arch=x86_64 target=release_debug
