name: Godot Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Disable GitPlugin in CI (sed fix)
        run: |
          sed -i 's/version_control\/plugin_name="GitPlugin"/version_control\/plugin_name=""/' project.godot

      - name: Print Godot version
        run: godot --version

      - name: Parse project scenes and scripts
        run: godot --headless --version

      - name: Parse project scenes and scripts v2
        run: godot --headless -q --check-only

      - name: Run headless build
        run: godot --headless -e -q
