name: Godot Headless Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  headless-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot binary
        id: godot-cache
        uses: actions/cache@v3
        with:
          path: godot
          key: godot-4.2.2-mono

      - name: Download Godot if not cached
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          wget -O godot.zip https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_mono_linux_x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.2.2-stable_mono_linux_x86_64/Godot_v4.2.2-stable_mono_linux.x86_64 

      - name: Run headless project load (smoke test)
        run: |
          ./godot/Godot_v4.2.2-stable_mono_linux_x86_64/Godot_v4.2.2-stable_mono_linux.x86_64  \
            --headless --editor --quit --path .
