name: Godot GDScript Headless Check

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Godot Headless
        run: |
          curl -LO https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux_headless.64.zip
          unzip Godot_v4.2.2-stable_linux_headless.64.zip
          chmod +x Godot_v4.2.2-stable_linux_headless.64
          mv Godot_v4.2.2-stable_linux_headless.64 godot

      - name: Disable GitPlugin in CI
        run: |
          sed -i 's/version_control\/plugin_name="GitPlugin"/version_control\/plugin_name=""/' project.godot || true
          sed -i 's/version_control\/autoload_on_startup=true/version_control\/autoload_on_startup=false/' project.godot || true

      - name: Run Godot Headless Validation
        run: ./godot --headless -q --check-only --path .
